# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH

- name: Prerequisites for Ansible Demos
  hosts: localhost
  connection: local
  tasks:

  - name: First make sure resource group is empty
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
      force: yes
      state: absent

  - name: Create a new resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
