- name: Deploy Mattermost Infrastructure Virtual Machines
  hosts: localhost
  connection: local

  tasks:
  - name: Create Mattermost VNet
    azure_rm_virtualnetwork:
      resource_group: '{{ resource_group }}'
      name: MMVNet
      address_prefixes: "10.10.0.0/16"

  - name: Create Mattermost Subnet
    azure_rm_subnet:
      resource_group: '{{ resource_group }}'
      name: MMSubnet
      address_prefix: "10.10.0.0/24"
      virtual_network: MMVNet

  - name: Create Mattermost Server & Proxy VM Public IP Address
    azure_rm_publicipaddress:
      resource_group: '{{ resource_group }}'
      name: '{{ vm_publicip_name }}'
      allocation_method: Static
      domain_name: '{{ vm_publicip_name }}'

  - name: Create Mattermost Server & Proxy NSG
    azure_rm_securitygroup:
      resource_group: '{{ resource_group }}'
      name: '{{ vm_name }}-nsg'
      rules:
          - name: 'AllowMatterMost'
            access: Allow
            destination_port_range: 8065
            direction: Inbound
            priority: 1010
            protocol: Tcp
          - name: 'AllowSSH'
            access: Allow
            destination_port_range: 22
            direction: Inbound
            priority: 1011
            protocol: Tcp

  - name: Create Mattermost Server & Proxy VM NIC
    azure_rm_networkinterface:
      name: '{{ vm_name }}-nic'
      os_type: Linux
      public_ip_address_name: '{{ vm_publicip_name }}'
      resource_group: '{{ resource_group }}'
      security_group_name: '{{ vm_name }}-nsg'
      subnet_name: MMSubnet
      virtual_network_name: MMVnet

  - name: Create Mattermost Server & Proxy VM
    azure_rm_virtualmachine:
      admin_username: "{{ admin_username }}"
      location: '{{ location }}'
      managed_disk_type: Standard_LRS
      name: '{{ vm_name }}'
      network_interface_names: '{{ vm_name }}-nic'
      os_type: Linux
      resource_group: '{{ resource_group }}'
      short_hostname: '{{ vm_name }}'
      vm_size: Standard_DS3_v2
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/{{ admin_username }}/.ssh/authorized_keys
          key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      image:
        offer: RHEL
        publisher: RedHat
        sku: '7-LVM'
        version: 7.4.2018010506
      data_disks:
        - lun: 0
          disk_size_gb: 100
          managed_disk_type: Premium_LRS
