# Description
# ===========
# This playbook creates an Application Gateway.

---
- hosts: localhost
  tasks:

    - name: Sample for Azure REST API - VirtualMachineScaleSets_CreateOrUpdate
      azure_rm_resource:
        # url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}
        api_version: '2017-12-01'
        resource_group: "{{ resource_group }}"
        provider: compute
        resource_type: virtualmachinescalesets
        resource_name: "{{ vmss_name }}"
        body:
          sku: 
            tier: Standard
            capacity: 2
            name: Standard_DS1_v2
          location: "{{ location }}"
          properties: 
            overprovision: true
            virtualMachineProfile: 
              storageProfile: 
                imageReference: 
                  id:  "/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/images/{{ vm_image_name }}"
                osDisk: 
                  caching: ReadWrite
                  managedDisk: 
                    storageAccountType: Standard_LRS
                  createOption: FromImage
              osProfile: 
                computerNamePrefix: vmsstest
                adminUsername: "{{ admin_username }}"
                adminPassword: "{{ admin_password }}"
              networkProfile: 
                networkInterfaceConfigurations: 
                  - name: vmsstest
                    properties: 
                      primary: true
                      enableIPForwarding: true
                      ipConfigurations: 
                        - name: default
                          properties: 
                            applicationGatewayBackendAddressPools: 
                              - id: "/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/applicationGateways/{{ appgateway_name }}/backendAddressPools/test_backend_address_pool"
                            subnet: 
                              id: "/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ vnet_name }}/subnets/{{ vmss_name }}"
            upgradePolicy: 
              mode: Manual
    
