- hosts: localhost
  tasks:
    - debug:
        var: output

    - name: Sample for Azure REST API - ApplicationGateways_Get
      azure_rm_resource_facts:
        # url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/applicationGateways/{applicationGatewayName}
        api_version: '2018-01-01'
        resource_group: "{{ resource_group }}"
        provider: network
        resource_type: applicationgateways
        resource_name: "{{ appgateway_name }}"
      register: output
    
    - debug:
        var: output