
---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Password@123
      network_interfaces: "{{ vm_name }}"
      storage_account_name: zimsstorageaccx
      storage_container_name: vhds
      storage_blob: blob.vhd
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest

  # do whatever is necessary to this vm
  - name: Stop VM before it can be geenralized and image captured
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      started: no

  - name: Call REST API - VirtualMachines_Generalize
    azure_rm_resource:
      # url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/generalize
      api_version: '2017-12-01'
      method: POST
      resource_group: "{{ resource_group }}"
      provider: compute
      resource_type: virtualmachines
      resource_name: "{{ vm_name }}"
      subresource:
        - type: generalize
  
  - name: Create an image from a virtual machine
    azure_rm_image:
      resource_group: "{{ resource_group }}"
      name: zimsvmimage
      source: "{{ vm_name }}"
