# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH

- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:

  - name: First make sure resource group is empty
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
      state: absent

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
